### ISSUE TITLE
Add delete button

### ISSUE THREAD

**Issue by HansBambel** [khaleelasyraaf/Mobius_Client#13]
I think it would be useful to be able to delete the latest (or all?) recording. For example when you want to show the app to someone or want to test it out you can delete it afterwards.

**Comment by khaleelasyraaf** [comment]
Good idea. I'll work on that.

**Comment by khaleelasyraaf** [comment]
Done. When pressing the "Upload" button, an option to delete the files will show up. It also resets the chronometer.
