### ISSUE TITLE
More efficient save of files

### ISSUE THREAD

**Issue by HansBambel** [khaleelasyraaf/Mobius_Client#2]
Currently files are very huge due to the JSON format.

Idea:
**Store the values on the phone line by line with the datetime and only later cast them to the format needed for the Visual Inspection Tool**

**Comment by dimstudio** [comment]
What is the activity? At what point is data serialised into JSON? we should try to only keep JSON compressed because compressed folders solve the verbosity of the JSON format.

**Comment by HansBambel** [comment]
The thing is that we store the sensor readings in the JSON format for the VIP. Only when the readings are stopped (which we planned to be for 10 hours) we zip the JSON.
But stopping after 30 seconds already ends up being a 0.5mb file. 

Furthermore, we can not save it as proper JSON, because right now we are just appending to the file. To be a proper JSON we would need to load the file in memory and append the new sensor reading. But a phone has limited RAM, which makes it impossible for larger files

**Comment by dimstudio** [comment]
Got it. Some time ago, I was proposing this new, more concise format, let me know what do you think?
```
{
  "recordingID": "2018-12-2-13H3M57S41",
  "applicationName": "Myo",
  "frameAttributes": ["Orientation_W", "Orientation_X", "Orientation_Y", "Orientation_Z", "Accelerometer_X"] 
  "frames": [
    {
      "frameStamp": "00:00:00.0160129",
      "frameValues": [ "0.08764648",  "-0.8060303", "-0.8060303", "-0.8060303", "-0.8060303"]
    },
    {
      "frameStamp": "00:00:00.0160129",
      "frameValues": [ "0.08764648",  "-0.8060303", "-0.8060303", "-0.8060303", "-0.8060303"]
    },

```

**Comment by dimstudio** [comment]
Or alternatively, we can follow your proposal, I think it makes more sense than changing the JSON format

**Comment by HansBambel** [comment]
> Got it. Some time ago, I was proposing this new, more concise format, let me know what do you think?
> 
> ```
> {
>   "recordingID": "2018-12-2-13H3M57S41",
>   "applicationName": "Myo",
>   "frameAttributes": ["Orientation_W", "Orientation_X", "Orientation_Y", "Orientation_Z", "Accelerometer_X"] 
>   "frames": [
>     {
>       "frameStamp": "00:00:00.0160129",
>       "frameValues": [ "0.08764648",  "-0.8060303", "-0.8060303", "-0.8060303", "-0.8060303"]
>     },
>     {
>       "frameStamp": "00:00:00.0160129",
>       "frameValues": [ "0.08764648",  "-0.8060303", "-0.8060303", "-0.8060303", "-0.8060303"]
>     },
> ```

The problem with "streaming" into the file also persists there. It will be smaller, but still quite large.

Also: Why are the values stored as strings? It would be better to store them as floats in the first place.

**Comment by dimstudio** [comment]
Again this format has been chosen for simplicity, not for optimization reasons. What is your proposal?

**Comment by HansBambel** [comment]
My proposal is to record the sensor readings and store the values in a csv like format:
```
Time, Acc_x, Acc_y, Acc_z, Gyro_x, Gyro_y, Gyro_z
2020-03-27T13:37.123,-1.147,0.125,-8.741,-5.2441,3.123,9.874
2020-03-27T13:37.254,-1.174,-0.125,-4.741,-1.2441,3.123,7.454
```
And load this file to the server (or zip it before. Not sure whether zipping saves space). Then, we run a script (still needs to be made) that takes the file as input and creates JSON that are readable for the VIP.
